FROM quay.io/jupyter/datascience-notebook:2024-11-19

# Install only training deps
RUN pip install \
    pandas==2.2.3 \
    alpaca-py==0.33.1 \
    prophet==1.1.6 \
    plotly==5.24.1 \
    statsmodels==0.14.4
